mode: train

dataset:
  root: /kaggle/input/mvtec-ad
  category: leather

student_training:
  epochs: 100
  batch_size: 32

triplet_training:
  epochs: 100
  batch_size: 32

heatmap_threshold:
  method: percentile
  value: 95.0

models:
  st_path: null
  tl_path: null
  calibration: null

box: 
  expand: 0.5
  min_area: 600

nms:
  mode: mean
  score_thr: 0.1
  thr: 0.4
