mode: train

dataset:
  mvtec_path: /kaggle/input/mvtec-ad
  mvtec_category: cable
  ok_crops: /kaggle/crops/ok
  notok_crops: /kaggle/crops/not_ok
  ok_manifest: /kaggle/crops/ok_manifest.csv
  notok_manifest: /kaggle/crops/notok_manifest.csv
  

student:
  train: true,
  epochs: 100
  batch_size: 32
  lr: 0.4
  momentum: 0.9
  weight_decay: 1e-4
  checkpoint: null
  calibration: null

triplet:
  train: true,
  epochs: 100
  batch_size: 32
  lr: 0.001
  weight_decay: 1e-4
  margin: 1.0
  checkpoint: null

heatmap_threshold:
  method: percentile
  value: 95.0

box: 
  expand: 0.05
  min_area: 600

nms:
  mode: mean
  score_thr: 0.1
  thr: 0.4

